// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"neko-tool/internal/api"
	providers2 "neko-tool/internal/api/providers"
	"neko-tool/internal/app"
	"neko-tool/internal/config"
	"neko-tool/internal/core/ds/providers"
	"neko-tool/internal/repository"
	"neko-tool/internal/service"
)

// Injectors from wire.go:

func InitializeApp() *app.ApplicationHolder {
	applicationConfigManager := config.NewApplicationConfigManager()
	accessAuthService := service.NewAccessAuthService(applicationConfigManager)
	authApi := api.NewAuthApi(accessAuthService)
	multiDataSource := providers.NewMultiDataSource()
	dataSource := providers.GetPrimaryDataSource(multiDataSource)
	workSpaceRepository := repository.NewWorkSpaceRepository(dataSource)
	workSpaceService := service.NewWorkSpaceService(workSpaceRepository)
	projectAccessService := service.NewProjectAccessService(applicationConfigManager)
	projectNodeCacheRepository := repository.NewProjectNodeCacheRepository(dataSource)
	projectSyncLogRepository := repository.NewProjectSyncLogRepository(dataSource)
	projectSyncLogService := service.NewProjectSyncLogService(projectSyncLogRepository)
	serverNodeRepository := repository.NewServerNodeRepository(dataSource)
	serverNodeService := service.NewServerNodeService(serverNodeRepository)
	nodeClientService := service.NewNodeClientService(serverNodeService, applicationConfigManager)
	projectBrowserCacheService := service.NewProjectBrowserCacheService(workSpaceService, projectAccessService, projectNodeCacheRepository, projectSyncLogService, nodeClientService, applicationConfigManager)
	projectApi := api.NewProjectApi(workSpaceService, projectAccessService, projectBrowserCacheService)
	nodeApi := api.NewNodeApi(serverNodeService, nodeClientService)
	compareService := service.NewCompareService(workSpaceService, projectAccessService, nodeClientService, serverNodeService, projectSyncLogService)
	compareApi := api.NewCompareApi(compareService, projectBrowserCacheService, applicationConfigManager)
	siteInfoService := service.NewSiteInfoService(applicationConfigManager)
	siteApi := api.NewSiteApi(siteInfoService, compareService)
	v := providers2.ProvideApis(authApi, projectApi, nodeApi, compareApi, siteApi)
	appWebManager := app.NewAppWebManager(applicationConfigManager, accessAuthService, v)
	applicationHolder := app.NewApplicationHolder(applicationConfigManager, appWebManager)
	return applicationHolder
}
